server:
  port: 8000
spring:
  # DRIVE MYSQL, E CONFIGURAÇÕES FLYWAY
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio-service?useTimezone=true&serverTimezone=UTC
    username: joselui3
    password: 840318Bd@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: cambio-service
    user: joselui3
    password: 840318Bd@
